# Use NGINX as the base image
FROM nginx:alpine

# Copy the HTML file to the NGINX server's default HTML directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 to allow access to the web server
EXPOSE 80
